### ISSUE TITLE
Running `kevm solc-to-k ...` in KEVM requires rebuilding venv

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1232]
I am trying to run:

```
kevm solc-to-k tests/solc-to-k/vat.sol Vat
```

on a given contract in the repository. I have `kevm` on my `PATH`, and have done:

```
make kevm-pyk-venv -B
. ./kevm_pyk/venv-prod/bin/activate
```

Then I run the `solc-to-k` command and there is a bug. So I fix `kevm_pyk/src/kevm_pyk/solc_to_k.py`. I then have to re-run `make kevm-pyk-venv -B` for my changes to be picked up, which also re-installs `pyk` dependencies, for example, and it doesn't need to for this simple change.

**Comment by tothtamas28** [comment]
I see two solutions.

1, We can install `kevm_pyk` in [editable mode](https://pip.pypa.io/en/stable/cli/pip_install/#editable-installs) so that reinstalling it on change is not necessary.
2. We can define a `make` target that reinstalls `kevm_pyk`.

I suggest we implement solution 1, and fall back to solution 2 if it editable mode has some drawback that we do not foresee.
