### ISSUE TITLE
Single-letter contract names fail frequently

### ISSUE THREAD

**Issue by david-k** [runtimeverification/evm-semantics#1368]
Assume we have a Foundry test in file `test/MyTest.t.sol`:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";

contract F { }

contract MyTest is Test { }
```

If we run
```sh
forge build
kevm foundry-kompile out/ \
    --require lemmas/int-simplification.k --module-import INT-SIMPLIFICATION \
    --require lemmas/lemmas.k --module-import LEMMAS

```
the following error is generated:
```
[Error] Inner Parser: Parse error: unexpected token 'F' following token '('.
        Source(/home/david/RV/evm-semantics/.build/usr/lib/kevm/include/kframework/lemmas/int-simplification.k)
        Location(115,48,115,49)
        115 |       rule (E *Int A) +Int B +Int C +Int D +Int (F *Int A) => ((E +Int F)
*Int A) +Int B +Int C +Int D [simplification]
            .                                                  ^
[Error] Compiler: Had 1 parsing errors.

...
```
However, if we move the definition of contract `F` into its own file under `src/` then the error disappears.

**Comment by ehildenb** [comment]
This is actually because of the contract named `F`, not because of he missing `Test` inheritance. `foundry-kompile` generates a K definition, with `syntax Contract ::= "F"`, and then when parsing the listed rule, the K parser is confused because it is not sure if `F` is a variable or the declared constant.

I think in this case, K's parser should be able to figure this one out. https://github.com/runtimeverification/k/issues/2867
