### ISSUE TITLE
Required z3 version

### ISSUE THREAD

**Issue by enzoevers** [runtimeverification/evm-semantics#1499]
The current readme of this repository states that the required z3 version is v4.8.15. However, when building Solidity (0.8.17) from source, it requires z3 >= v4.8.16 due to the introduction of `Z3_OP_RECURSIVE ` (see the related issue https://github.com/ethereum/solidity/issues/13178).

> For context. I'm building `solc` from source since I'm creating a docker image with different smart-contract analysis tools (of which kevm is one) and it needs to run on both x86_64 and arm (M1). The Rust [svm](https://github.com/roynalnaruto/svm-rs) solc installer supports aarch64, but it doesn't enable dynamic loading of z3/cvc4. So that's why I'm building from source.

So I installed z3 v4.8.16 instead of v4.8.15 and it turns out that `kevm prove --backend haskell ...` works 'just fine' with z3 v4.8.16. Is there a reason that z3 v4.8.15 is still stated in the readme? As in, are other features of kevm not compatible (yet) with z3 v4.8.16?

Otherwise, I think it would be nice to update the required z3 version of kevm to be compatible with the latest solc versions.

**Comment by Baltoli** [comment]
We've had problems with slightly broken Z3 versions in the past, and so our solution has been to pin a particular version until we run into an issue like this. You can almost certainly use v4.8.16 just fine.

I'll look at propagating the upstream K tools to a newer version so that we can update the instructions.
