### ISSUE TITLE
Expose JSON-RPC endpoints for `kevm foundry` commands

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/evm-semantics#1580]
The `kevm` CLI then will have a flag `--kaas` for RPC client mode, e.g.

```
$ kevm foundry-prove --kaas HOST:PORT ...
```

**Comment by ehildenb** [comment]
@tothtamas28 it would also be good to expose the other `foundry-...` commands over RPC.

Or to create a separate `foundry ...` command which takes subcommands `['prove', 'show', 'view', 'step', 'section-edge', 'remove-node', 'simplify']`. That way we can just make the entire `foundry` command available over RCP.

**Comment by ehildenb** [comment]
So for example, `kevm foundry --kaas HOST:PORT remove-node ...` should do its operation on the remote files.

`kevm foundry --kaas HOST:PORT view ...` should pull the CFG from the remote, and launch the CFG viewer locally.

**Comment by tothtamas28** [comment]
> `kevm foundry --kaas HOST:PORT view ...` should pull the CFG from the remote, and launch the CFG viewer locally

This requires a kompiled definition on the client side: `KCFGViewer` uses `KPrint` to pretty-print configurations. Should we
a) assume the kompiled definition as a given on the client side, or
b) eliminate the dependency?

**Comment by ehildenb** [comment]
It sounds easier to assume kompiled definitions on both sides for now, so let's do that. Otherwise, we can shuttle terms over to the server and ask it to pretty-print them, and send them back, if you think that's reasonable to implement.

But I think for demo purposes, we can just assume that we do have access to a kompiled definition on both client and server side.
