### ISSUE TITLE
Implement infinite gas as a pointed set

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1653]
@andreas-blockswap pointed out that our lemmas for infinite gas are contradictory.

we have:

```
#gas(G) -Int #gas(G') => #gas(G -Int G')
#gas(X) <=Int #gas(Y) => true
A -Int A => 0
```

So these three lemmas together seem to say different things.

One solution, would be to have `#gas` be a constructor instead into the new `Gas` sort which is a supersort of `Int`.

**Comment by goodlyrottenapple** [comment]
I was actually wondering why we keep an expression inside `#gas`? Can't it just be some constant for which we have rules such as:
```
#gas -Int #gas => #gas
#gas <=Int #gas => true
```
?

**Comment by dkcumming** [comment]
Hi @ehildenb @andreas-blockswap,

After some consideration I am not entirely sure how the pointed set will solve the above problem. My initial understanding for how a pointed set would apply to this problem would be that $gas$ is represented as $(\mathbb{N}, gc \in \mathbb{N})$, where $\mathbb{N}$ is representing infinite gas as the set of natural number, and $gc$ accumulated gas consumed by the execution, but this is saying the same thing as before. Did I misunderstand how the pointed sets will apply to this problem?

After some thought and discussion with Jost, I feel the issue with the contradicting lemmas Everett mentioned is that the second lemma binary operator "<=Int" considers #gas an Int. The approach of a constructor for #gas with rules for operators +, -, *, / defined as applying to the gas consumed as Int operations, and <=,  >  defined returning a constant bool is sufficient I believe. 

I will work on the constructor approach for now as that path feels clear, but if I have overlooked the pointed set approach please let me know how it will apply.

**Comment by andreas-blockswap** [comment]
The idea was that the pointed set structure would be $(\mathcal{G}, x_0)$, $x_0 \not\in \mathbb{Z}$ and $\mathcal{G} = \mathbb{Z} \cup \\{x_0\\}$. All the standard math operations, $+$, $-$, $\cdot$, are homomorphisms of pointed sets (maps point to point).

Negation $\mathcal{G} \to \mathcal{G}$ would map $a \mapsto x_0$ if $a = x_0$ and $a \mapsto -a$ otherwise.

Addition is in theory a homomorphism with smash product domain $\mathcal{G} \wedge \mathcal{G} \to \mathcal{G}$, but in practice implemented as a function with product domain $\mathcal{G} \times \mathcal{G} \to \mathcal{G}$, such that $(a,b) \mapsto x_0$ if $a = x_0$ or $b = x_0$ and otherwise $(a,b) \mapsto a + b$.

My guess is that the constructor implementation you have in mind is similar.

**Comment by ehildenb** [comment]
I think the constructor approach _is_ the pointed set approach. Basically, amke a supersort `Gas` of sort `Int`, that has one more element. That single element is `#gas(_:Int)`. Then lift operators `_+Int_`, `_-Int_` , etc... to `_+Gas_`, `_-Gas_`, ....

If the arguments of an operator like `_+Gas_` are both `Int`, then you use `_+Int_` directly, with a rule like `rule G1 +Gas G2 => G1 +Int G2` (no need for sort annotations, because the occurrences of `G1` and `G2` on the RHS restrict it to being sort `Int`).


But then you have rules:

```
rule #gas(G1) +Gas G2 => #gas(G1 +Int G2)
rule G1 +Gas #gas(G2) => #gas(G1 +Int G2)
rule #gas(G1) +Gas #gas(G2) => #gas(G1 +Int G2)
```

etc....

These rules implement the "pointed set" semantics, that is: _any_ operation in the set that involves the _point_ `#gas(_)` returns the point `#gas(_)` (the extra argument to `#gas(_)` is irrelevant for the semantics, we want it for logistic purposes of tracking gas consumed).
